### PR TITLE
Add support for null filter values

### PR DESCRIPTION
**Pull request by topermaper**
Hi @exleym ,

I have prepared a fix in order to make equal and not_equal filters support null values.
Could you please take a look to it when you have time and review it?

Cheers,
Marcos

### CODE REVIEW

**Comment by exleym** [comment]
@topermaper first off, this looks great. thanks for putting it together! 

One question before we merge and release: do you think it makes more sense to make "=" and "!=" nullable or to make separate operators for null checks? 

I don't really have a prior here, and I'm okay with it either way, but it popped into my head while reviewing that it might make sense to have "is null" and "is not null" be explicit operators rather than equality checks.

**Comment by topermaper** [comment]
@exleym

I think we could treat null like any other value so we can reuse comparation operator.
It could also be done as you suggested but I can not see much benefit.
Also if we used an "isnull" operator then the value field would be useless (null would already be implicit) and the filter format would not be consistent thus changing depending on which operator is used.

**Comment by exleym** [comment]
The point about the schema inconsistency is valid and IMO outweighs the value of differentiating between null and "real" values. I'm good with this.

**Review by exleym — APPROVED** [review]

**Comment by topermaper** [comment]
Hi Exley,

I just added Flask-Filter==0.1.2a3 to my requirements.txt file and the fix
worked like a charm.

As a temporary fix I had imported all your library code into my project
shared/lib folder, made the changes locally and added to the path like this:

# Include libraries
base_dir = os.path.abspath(os.path.dirname(__file__))
lib_dir = os.path.join(base_dir, 'shared/lib')
sys.path.append(lib_dir)

This didn't look nice to me even though it worked so I was wondering what
else I could have done in case you didn't want to help me updating the
library. Isn't it possible somehow to clone your library, make the changes
and add something like "topermaper/Flask-Filter" to my requirements file?
I'm just curious about this but thank you so much for your help in any case.

Cheers,
Marcos

**Pull request merged**
